//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PchK22CNT3Lesson12_2210900101.Content
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PHAMCONGHIEU_2210900101Entities1 : DbContext
    {
        public PHAMCONGHIEU_2210900101Entities1()
            : base("name=PHAMCONGHIEU_2210900101Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pch_Sach> Pch_Sach { get; set; }
        public virtual DbSet<Pch_TacGia> Pch_TacGia { get; set; }
    }
}
