//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PchK22CNT3Lesson12_2210900101.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pch_TacGia
    {
        public string Pch_MaTG { get; set; }
        public string Pch_TenTacGia { get; set; }
    }
}
